#!/bin/bash

cd "$(dirname "$0")"

if [ -f ".env" ]; then
  export $(grep -v '^#' .env | xargs -d '\n')
fi

if [ "$1" = "run" ]; then
  echo "Running..."
  go run bake/a/cake.go
elif [ "$1" = "build" ]; then
  echo "Building..."
  mkdir -p build
  go build -o build/ a/strawberry/cake.go
else
  echo "Shiver me timbers!!.. Invalid arrghh: $1"
  exit 1
fi




